In [2]:
import pandas as pd

In [3]:
df =  pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [4]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Numpy Arrays

### Creating Arrays

In [5]:
import numpy as np

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  4,  5])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dimensional arrays

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array(
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
n[0,1] = 20

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
# accessing rows 
n[2] = [1,1,1]


In [21]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
# getting all rows from the second column
n[:,1]

array([20,  5,  1])

In [23]:
# replacing a specific column
n[:,2] = [0,1,2]

### randomly generated arrays

In [24]:
np.random.rand(5,2)

array([[0.47806828, 0.00232182],
       [0.08667415, 0.96229597],
       [0.19312142, 0.60827873],
       [0.29161365, 0.66424456],
       [0.78566607, 0.80399347]])

In [25]:
# maintaining the random state without chnaging the results every time
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [26]:
# random negative numbers
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [27]:
# Multiplying the entire array by 100
100 * np.random.rand(5,2)

array([[62.11338328, 52.91420943],
       [13.45799453, 51.35781213],
       [18.44398656, 78.53351478],
       [85.39752926, 49.42368374],
       [84.65614854,  7.9645477 ]])

In [28]:
# random integers
np.random.seed(2)
np.random.randint(low = 0 , high = 100, size =(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise Operations

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
a+1

array([1, 2, 3, 4, 5])

In [31]:
a*100

array([  0, 100, 200, 300, 400])

In [32]:
a/100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [33]:
(10+(a*2))**2

array([100, 144, 196, 256, 324])

In [34]:
b = (10+(a*2))**2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [36]:
a >= 2

array([False, False,  True,  True,  True])

In [37]:
a > b

array([False, False,  True,  True,  True])

In [ ]:
# the 
a[a> b]

array([2, 3, 4])

### Summarizing operations

In [40]:
a

array([0, 1, 2, 3, 4])

In [47]:
a.min()

np.int64(0)

In [45]:
a.max()

np.int64(4)

In [48]:
a.sum()

np.int64(10)

In [49]:
a.mean()

np.float64(2.0)

In [50]:
a.std()

np.float64(1.4142135623730951)